apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: file-share
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-sc 
  resources:
    requests:
      storage: 50Gi