apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: minio-sc
  hostPath:
    path: "/mnt/data/postgres"
