apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-service
  namespace: file-share
spec:
  type: NodePort
  ports:
  - name: db
    port: 5432
  selector:
    app: postgres