apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-script
  namespace: file-share
data:
  psql-script.sh: |-
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE keycloak;
        GRANT ALL PRIVILEGES ON DATABASE keycloak TO postgres;
    EOSQL
    
    
